version: 2.1

jobs:
  build-and-upload:
    machine: true
    parameters:
      github:
        type: boolean
    steps:
      - run: echo << parameters.github >>
                   
workflows:
  main:
    jobs:
      # Run job when this is merge to master
      - build-and-upload:
          context: bré
          github: true
          filters:
            branches:
              only:
                - master
      # Run job when this is an API call from CD service
      - build-and-upload:
          context:
             - bré
             - toto
          github: false
