version: 2.1

orbs:
    browser-tools: circleci/browser-tools@1.1.3
    
commands:
  install_chrome_browser:
    description: Reusable command to handle Chrome browser install
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: latest
          install-chromedriver: true
          install-firefox: false
          install-geckodriver: false
      - run: npm install chromedriver --detect_chromedriver_version

jobs:
  myjob:
    docker:
      - image: cimg/node:14.18-browsers
    steps:
      - install_chrome_browser

workflows:
  build-toto:
    jobs:
      - myjob
      
