version: 2.1

jobs:
  build:
    machine: true
    steps:    
      - run:
          name: Install OpenJDK 11 Yo yo
          command: |
            #sudo apt-get update && sudo apt-get install openjdk-11-jdk
            #sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            #sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
            java -version
            lsb_release -a


                   
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
