version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: yaningo/ubuntu-1804
    steps:
      - run: |
          echo "Hi I'm on Runners!"
          echo "My IP is $(curl -s https://checkip.amazonaws.com/)"
          
      - run: echo "Now Tines, do your thing!"
