version: 2.1
workflows:
  testing:
    jobs:
      -test
jobs:
  -test:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - run: |
          node --version
          java --version
          google-chrome --version
