version: 2

jobs:
  ruby_265:
    docker:
    - image: circleci/ruby:2.6.5-stretch-node-browsers
    steps:
      - run:
          command: |
                   google-chrome --version
                   #dockerize -wait tcp://localhost:9515 -timeout 1m
                   
                   
  ruby_266:
    docker:
    - image: circleci/ruby:2.6.6-stretch-node-browsers
    steps:
      - run:
          background: true
          name: Launching ChromeDriver
          command: chromedriver
                   
      - run:
          command: |
                   dockerize -wait tcp://localhost:9515 -timeout 1m
                   google-chrome --version
                   chromedriver --version
                   
                   
workflows:
  version: 2
  build_265:
    jobs:
      - ruby_265
      
  build_265:
    jobs:
      - ruby_266
