version: 2.1

commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: echo Hello << parameters.to >>

jobs:
  myjob:
    docker:
      - image: "cimg/base:stable"
    steps:
      - sayhello: # invoke command "sayhello"
          to: << parameters.to >>

workflows:
  build-toto:
    jobs:
      - myjob:
          to: Toto
          
  build-titi:
    jobs:
      - myjob:
          to: Titi
      
