version: 2.1

orbs:
  android: circleci/android@0.2.3

jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:    
      - run:
          name: Install OpenJDK 8 Yo yo
          command: |
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C2518248EEA14886
            sudo sh -c 'echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" > /etc/apt/sources.list.d/webupd8team-java.list'
            sudo sh -c 'echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" > /etc/apt/sources.list.d/webupd8team-java.list'
            sudo apt-get update
            sudo apt-get install oracle-java8-installer
            java -version
                    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
