version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: yaningo/macbook
    steps:
      - run: echo "Hi I'm on a macOS CircleCI Runner! Yay"
