version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:    
      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt-get update && sudo apt-get install openjdk-11-jdk
            java -version
            sudo update-alternatives --config java

                   
workflows:
  build_and_test:
    jobs:
      - build
