version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:    
      - run:
          name: Install OpenJDK 14
          command: |
            pwd
            wget https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz
            sudo tar -zxvf openjdk-14.0.2_linux-x64_bin.tar.gz
            sudo update-alternatives --install /usr/bin/java java /home/circleci/project/jdk-14.0.2/bin/java 100
            sudo update-alternatives --install /usr/bin/javac javac /home/circleci/project/jdk-14.0.2/bin/javac 100
            #sudo update-alternatives --config java
            #sudo update-alternatives --set java /home/circleci/project/jdk-14.0.2/bin/java
            sudo update-alternatives --set javac /home/circleci/project/jdk-14.0.2/bin/javac
            java -version
                   
workflows:
  build_and_test:
    jobs:
      - build
