version: 2.1

orbs:
  android: circleci/android@0.2.3

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:    
      - run:
          name: Install OpenJDK 8 Yo yo
          command: |
            sudo apt-get update && sudo apt-get install openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            java -version
                    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
