version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:    
      - run:
          name: Check OpenJDK version
          command: |
            java -version

workflows:
  build_and_test:
    jobs:
      - build
