version: 2.1

jobs:
  ruby_265:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node-browsers
    steps:
      - run:
          command: |
                   google-chrome --version
                   
  ruby_266:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node-browsers
    steps:
      - run:
          command: |
                   google-chrome --version
 

workflows:
  version: 2
  265:
    jobs:
      - ruby_265
      
  266:
    jobs:
      - ruby_266
