version: 2.1

orbs:
  macos: circleci/macos@2.4.1

workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    macos:
      xcode: 14.1.0
    # machine: true
    # resource_class: yaningo/macbook
    steps:
      - run: ruby -v
      - run: |
          HOMEBREW_NO_AUTO_UPDATE=1 ruby-install ruby 3.2
          #brew install ruby
          #echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> /Users/distiller/.bash_profile
      - macos/switch-ruby:
          version: "3.2"
      - run: ruby -v
