version: 2.1

parameters:
  github:
    type: boolean
    default: true
jobs:
  build-and-upload:
    machine: true
    steps:
      - run: echo << pipeline.parameters.github >>
                   
workflows:
  main-1:
    when: equal [ true, << pipeline.parameters.github >> ]
    jobs:
      # Run job when this is merge to master
      - build-and-upload:
          context: bré
 
  main-2:
    when:  equal [ false, << pipeline.parameters.github >> ]
    jobs:
      # Run job when this is an API call from CD service
      - build-and-upload:
          context:
             - bré
             - toto
