version: 2.1

jobs:
  ruby_265:
    docker:
    - image: circleci/ruby:2.6.5-stretch-node-browsers
    steps:
      - run:
          command: |
                   google-chrome --version
                   #dockerize -wait tcp://localhost:9515 -timeout 1m
                   sleep 10
                   curl -G 'https://circleci.com/api/v2/pipeline/<<pipeline.id>>/workflow' -H 'Circle-Token: $MyToken'|jq -s --arg CIRCLE_WORKFLOW_ID "$CIRCLE_WORKFLOW_ID" '.[].items[]|select(.id != $CIRCLE_WORKFLOW_ID)|.id'
                   
                   
  ruby_266:
    docker:
    - image: circleci/ruby:2.6.6-stretch-node-browsers
    steps:
      - run:
          background: true
          name: Launching ChromeDriver
          command: chromedriver
                   
      - run:
          command: |
                   dockerize -wait tcp://localhost:9515 -timeout 1m
                   google-chrome --version
                   sleep 10
                   curl -G 'https://circleci.com/api/v2/pipeline/<<pipeline.id>>/workflow' -H 'Circle-Token: $MyToken'|jq -s --arg CIRCLE_WORKFLOW_ID "$CIRCLE_WORKFLOW_ID" '.[].items[]|select(.id != $CIRCLE_WORKFLOW_ID)|.id'
                   
                   
workflows:
  version: 2
  build_265:
    jobs:
      - ruby_265
      - hold265: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval
          requires:
            - ruby_265
          post-steps:
            - run:
                name: Cancel the other "on_hold_workflow"
                command: |
                    #other_on_hold_id=$(curl --location --request GET 'https://circleci.com/api/v2/pipeline/<<pipeline.id>>/workflow' -H 'Circle-Token: $MyToken'|jq -s --arg CIRCLE_WORKFLOW_ID "$CIRCLE_WORKFLOW_ID" '.[].items[]|select(.status == "on_hold")|select(.id != $CIRCLE_WORKFLOW_ID)|.id')
                    curl -G 'https://circleci.com/api/v2/pipeline/<<pipeline.id>>/workflow' -H 'Circle-Token: $MyToken'|jq -s --arg CIRCLE_WORKFLOW_ID "$CIRCLE_WORKFLOW_ID" '.[].items[]|select(.status == "on_hold")|select(.id != $CIRCLE_WORKFLOW_ID)|.id'
                    #curl -X POST 'https://circleci.com/api/v2/workflow/$other_on_hold_id/cancel' -H 'Circle-Token: $MyToken'
      
  build_266:
    jobs:
      - ruby_266
      - hold266: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval
          requires:
            - ruby_266
          post-steps:
            - run:
                name: Cancel the other "on_hold_workflow"
                command: |
                    #other_on_hold_id=$(curl --location --request GET 'https://circleci.com/api/v2/pipeline/<<pipeline.id>>/workflow' -H 'Circle-Token: $MyToken'|jq -s --arg CIRCLE_WORKFLOW_ID "$CIRCLE_WORKFLOW_ID" '.[].items[]|select(.status == "on_hold")|select(.id != $CIRCLE_WORKFLOW_ID)|.id')
                    curl -G 'https://circleci.com/api/v2/pipeline/<<pipeline.id>>/workflow' -H 'Circle-Token: $MyToken'|jq -s --arg CIRCLE_WORKFLOW_ID "$CIRCLE_WORKFLOW_ID" '.[].items[]|select(.status == "on_hold")|select(.id != $CIRCLE_WORKFLOW_ID)|.id'
                    #curl -X POST 'https://circleci.com/api/v2/workflow/$other_on_hold_id/cancel' -H 'Circle-Token: $MyToken'
