version: 2.1

jobs:
  instruqt-push:
    docker:
      - image: instruqt/cli:latest
    entrypoint: /bin/bash
    steps:
      - checkout
      - run: instruqt version

workflows:
  instruqt:
    jobs:
      - instruqt-push
