version: 2.1

jobs:
  build:
    machine: true
    steps:
      - run: |
          sudo uname -a
          sudo lsb_release -a
          
workflows:
  build_and_test:
    jobs:
      - build:
          post-steps:
            - run:
                name: Determine job duration
                command: |
                    echo $CIRCLE_BUILD_NUM
                    #curl -G "https://circleci.com/api/v2/project/gh/yaningo/chrome-version/job/$CIRCLE_BUILD_NUM" -H "Circle-Token: $MyToken" |jq -s '.[] |.duration'
