version: 2.1

orbs:
  wireguard: orbiously/wireguard@1.0.0
workflows:
  testing:
    jobs:
      - test
jobs:
  test:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - wireguard/setup
