version: 2.1

jobs:
  build-and-upload:
    machine:
      image: ubuntu-1604:202004-01
    parameters:
      github:
        type: boolean
    steps:
      - run:
          command: |
            echo << parameters.github >>
            echo ${bre_var}
            echo ${toto_var}
                   
workflows:
  main:
    jobs:
      # Run job when this is merge to master
      - build-and-upload:
          #github: true
          context: bré
          github: true
          filters:
            branches:
              only:
                - master

      # Run job when this is an API call from CD service
      - build-and-upload:
          #github: false
          context:
             - bré
             - toto
          github: false
