version: 2.1
jobs:
  build:
    docker:
    - image: cimg/go:1.18.7
    steps:
#       - run:
#           command: |
#             sudo sed -i '4 s/./#&/' /etc/apt/sources.list.d/github_git-lfs.list
#             sudo sed -i '5 s/./#&/' /etc/apt/sources.list.d/github_git-lfs.list
      - run: sudo apt-get update 
workflows:
  workflow:
    jobs:
    - build
