version: 2.1

parameters:
  switch:
    type: string
    default: NoSecret

jobs:
  test:
    docker:
      - image: cimg/base:2022.09
    steps:
      - run: echo ${!<< pipeline.parameters.switch >>}

workflows:
  main:
    jobs:
      - test
