version: 2.1
workflows:
  testing:
    jobs:
      - runner-test:
          filters:
            tags:
              only: /.*/
jobs:
  runner-test:
    machine: true
    resource_class: yaningo/ubuntu-1804
    steps:
      - run: |
          echo "Hi I'm on Runnersssss!"
          echo "My IP is $(curl -s https://checkip.amazonaws.com/)"
          
      - run: echo "Go go! Yup yup!"
