version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      name: Install OpenJDK 14
        - run: |
            sudo apt-get update
            sudo apt-get install openjdk-14-jdk
                   
workflows:
  build_and_test:
    jobs:
      - build
