version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:    
      - run:
          name: Install OpenJDK 14
          command: |
            wget https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz
            sudo tar -xvf openjdk-14.0.2_linux-x64_bin.tar.gz
            java -version
                   
workflows:
  build_and_test:
    jobs:
      - build
