version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:    
      - run:
          name: Do something
          command: |
            ls -al

workflows:
  build_and_test:
    jobs:
      - build:
          post-steps:
            - run:
                name: Get job duration
                command: |
                    echo $CIRCLE_BUILD_NUM
                    #curl -G "https://circleci.com/api/v2/project/gh/yaningo/chrome-version/job/$CIRCLE_BUILD_NUM" -H "Circle-Token: $MyToken" |jq -s '.[] |.duration'
                    #curl -G "https://circleci.com/api/v2/project/gh/yaningo/chrome-version/job/$CIRCLE_BUILD_NUM" -H "Circle-Token: $MyToken"|jq -s '.[]'
                    curl -G "https://circleci.com/api/v2/pipeline/<<pipeline.id>>/workflow" -H "Circle-Token: $MyToken"|jq -s '.[]'
