version: 2.1

jobs:
  mysql-check:
    docker:
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          max_allowed_packet: 32M

    steps:
#       - run:
#           name: Waiting for MySQL to be ready
#           command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: run query to check variable value
          command: |
            mysql -h 127.0.0.1 -u root --execute="SHOW VARIABLES LIKE 'max_allowed_packet';"
  
workflows:
  lewkflw:
    jobs:
      - mysql-check
