version: 2.1

jobs:
  mysql-check:
    docker:
      - image: cimg/base:2022.10
        environment:
          MYSQL_USER: root
          
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
        command: mysqld --max_allowed_packet=1G

    steps:
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt-get update && sudo apt-get install default-mysql-client
            
#       - run:
#           name: Waiting for MySQL to be ready
#           command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Set and check variable value
          command: |
            mysql -h 127.0.0.1 -u root --execute="SHOW VARIABLES LIKE 'max_allowed_packet';"
  
workflows:
  lewkflw:
    jobs:
      - mysql-check
