version: 2.1

jobs:
  mysql-check:
    docker:
      - image: cimg/php:8.1-browsers
        environment:
          MYSQL_USER: root
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          max_allowed_packet: 32M

    steps:
      - run:
          name: Waiting for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Install MySQL CLI and run query to check variable value
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u root --execute="SHOW VARIABLES LIKE 'max_allowed_packet';"
  
workflows:
  lewkflw:
    jobs:
      - mysql-check
