version: 2.1

orbs: 
  browser-tools: circleci/browser-tools@1.2.5

jobs:
  test:
    docker:
      - image: cimg/ruby:3.0.3-browsers
    steps:
      - browser-tools/install-chrome

workflows:
  damain:
    jobs:
      - test
