version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:    
      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt-get update && apt-cache search jdk

                   
workflows:
  build_and_test:
    jobs:
      - build
