version: 2.1

orbs:
  cypress: cypress-io/cypress@2.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_test_deploy: # this can be any name you choose
    circleci_ip_ranges: true
workflows:
  version: 2
  build_and_test:
    jobs:
      - cypress/run:
          circleci_ip_ranges: true
