version: 2.1

jobs:
  test:
    machine:
      image: windows-server-2022-gui:current
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - run: ls

workflows:
  main:
    jobs:
      - test
