version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:    
      - run:
          name: Install OpenJDK 14
          command: |
            sudo apt-get update
            sudo apt-cache search openjdk
                   
workflows:
  build_and_test:
    jobs:
      - build
