version: 2.1

jobs:
  ruby_265:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node-browsers
    steps:
      - run:
          command: |
                   google-chrome --version
                   curl http://localhost:9515
                   
  ruby_266:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node-browsers
    steps:
      - run:
          command: |
                   google-chrome --version
                   curl http://localhost:9515
                   
workflows:
  build_and_test:
    jobs:
      - ruby_265
      - ruby_266
